adjust dev_cd to trigger on new release
ghga-de/microservice-repository-template pull request #149
Opened 2023-03-30 13:11 UTC by dontseyit

[GDEV-1827](https://jira.verbis.dkfz.de/browse/GDEV-1827)

2023-03-30 13:40 UTC, KerstenBreuer requested changes
Thanks a lot. Looks great. For the automated update of repos relying on the template, could you add the dev_cd.yaml to the `.deprecated_files` and remove it from `.mandatory_files` and `.static_files` if needed. Moreover, could you add the cd.yaml to `.static_files`?

Have you checked this action on a dummy repo? Would be good to make sure if it works before rolling it out. Testing in the template repo will be difficult.

2023-03-30 13:40 UTC, KerstenBreuer commented on .github/workflows/dev_cd.yaml
>  name: Dev CD
Also rename the file to cd.yaml.

```suggestion
name: CD
```

2023-03-30 13:40 UTC, KerstenBreuer commented on .github/workflows/dev_cd.yaml
> +        name: Set up Python 3.x
```suggestion
        name: Set up Python 3.9
```

2023-03-30 13:40 UTC, KerstenBreuer commented on .github/workflows/dev_cd.yaml
> +          SEMVER_REGEX="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"
The regex suggested on https://semver.org/ is the following:

```suggestion
          SEMVER_REGEX="^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
```

2023-03-30 14:18 UTC, dontseyit commented
@KerstenBreuer 

I updated the branch with your suggestions. You can check again. 

For the tests, I have a personal sandbox repo generated from the template. https://github.com/dontseyit/white-mountains 
I tested there also with my docker hub. 

This is the run recent updates https://github.com/dontseyit/white-mountains/actions/runs/4565363578
and the docker images go to https://hub.docker.com/r/seyit/white-mountains/tags

2023-03-30 14:24 UTC, KerstenBreuer approved these changes
Great thanks.

2023-03-31 07:02 UTC, lkuchenb commented
Shall upgrade `docker/login-action@v2.0.0` to `docker/login-action@v2.1.0` while we're at it? The old version seems to trigger deprecation warnings from GitHub, maybe the newer one resolves that.

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

2023-03-31 07:10 UTC, lkuchenb requested changes

2023-03-31 07:10 UTC, lkuchenb commented on .github/workflows/cd.yaml
> +      - uses: docker/login-action@v2.0.0
```suggestion
      - uses: docker/login-action@v2.1.0
```

2023-03-31 11:38 UTC, dontseyit commented
These versions are updated in order to fix the save-state warning.

login-action v2.0.0 -> 2.1.0
setup-buildx-action v2.0.0 -> 2.5.0
build-push-action v3.0.0 -> 4.0.0

This is the latest test run with these versions
https://github.com/dontseyit/white-mountains/actions/runs/4574452267/jobs/8076087363

2023-03-31 11:39 UTC, lkuchenb approved these changes
Thanks, looks like all warnings are gone 👍

2023-04-03 10:58 UTC, KerstenBreuer approved these changes

2023-04-03 12:09 UTC, merged